spring.application.name=Java_3.1.2

spring.jpa.hibernate.ddl-auto=create-drop
spring.datasource.url=jdbc:mysql://localhost:3306/java_3.1.2
spring.datasource.username=root
spring.datasource.password=root